# Generated by Django 3.1.6 on 2024-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/%Y'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='uploads/%Y'),
        ),
    ]
