# Generated by Django 3.1.6 on 2023-03-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0005_auto_20230303_1428'),
        ('symmetry', '0002_auto_20230303_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='symmop',
            name='pdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symops', to='pdbase.pdb'),
        ),
    ]
