# Generated by Django 3.1.6 on 2023-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symmetry', '0005_auto_20230304_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitcell',
            name='projections',
            field=models.JSONField(null=True),
        ),
    ]
