# Generated by Django 3.1.6 on 2023-10-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0006_pdb_oligomer'),
        ('symmetry', '0006_unitcell_projections'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=100, null=True)),
                ('unit_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symmetry.unitcell')),
            ],
        ),
        migrations.CreateModel(
            name='ResidueContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.FloatField()),
                ('res1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescont1', to='pdbase.residue')),
                ('res2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescont2', to='pdbase.residue')),
                ('symop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescontacts', to='symmetry.symop')),
            ],
        ),
    ]
