# Generated by Django 3.1.6 on 2023-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symmetry', '0007_residuecontact_symop'),
    ]

    operations = [
        migrations.AddField(
            model_name='symop',
            name='sym_type',
            field=models.IntegerField(null=True),
        ),
    ]
