# Generated by Django 3.1.6 on 2023-12-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0006_pdb_oligomer'),
        ('symmetry', '0008_symop_sym_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('area', models.FloatField()),
                ('type1', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('chain1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ifaces1', to='pdbase.chain')),
                ('chain2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ifaces2', to='pdbase.chain')),
                ('pdb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='pdbase.pdb')),
            ],
        ),
        migrations.AddField(
            model_name='symop',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='InterfaceResidueContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mind', models.FloatField()),
                ('num_atoms', models.IntegerField()),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescontacts', to='symmetry.interface')),
                ('res1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifrc1', to='pdbase.residue')),
                ('res2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifrc2', to='pdbase.residue')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='symop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='symmetry.symop'),
        ),
    ]
