# Generated by Django 3.1.6 on 2022-07-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDdirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Directory with MD simulations', max_length=300)),
                ('note', models.TextField(help_text='Note on this directory', null=True)),
                ('atime', models.DateTimeField()),
                ('mtime', models.DateTimeField()),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MDtrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('amber', 'Amber'), ('gromacs', 'Gromacs')], help_text='What type of trajectory', max_length=10)),
                ('file', models.CharField(help_text='Directory with MD simulations', max_length=300)),
                ('note', models.TextField(help_text='Note on this trajectory', null=True)),
                ('atime', models.DateTimeField()),
                ('mtime', models.DateTimeField()),
                ('ctime', models.DateTimeField()),
                ('filesize', models.IntegerField()),
                ('totaltime', models.IntegerField()),
                ('num_atoms', models.IntegerField()),
                ('num_frames', models.IntegerField()),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='md.mddirectory')),
            ],
        ),
    ]
