# Generated by Django 3.1.6 on 2022-07-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdtrajectory',
            name='totaltime',
            field=models.FloatField(),
        ),
    ]
