# Generated by Django 3.1.6 on 2022-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0002_auto_20220731_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdtrajectory',
            name='filesize',
            field=models.BigIntegerField(),
        ),
    ]
