# Generated by Django 3.1.6 on 2022-08-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0003_auto_20220801_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mddirectory',
            options={'ordering': ['-atime']},
        ),
        migrations.AlterModelOptions(
            name='mdtrajectory',
            options={'ordering': ['-atime']},
        ),
    ]
