# Generated by Django 3.1.6 on 2022-11-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('md', '0004_auto_20220812_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorsionAngle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.CharField(help_text='TorsionAngle file', max_length=300)),
                ('values', models.JSONField()),
                ('trajectory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torsions', to='md.mdtrajectory')),
            ],
        ),
    ]
