# Generated by Django 3.1.6 on 2022-11-01 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Objective'), ('M', 'Milestone'), ('D', 'Deliverable'), ('R', 'Result')], max_length=10)),
                ('tag', models.IntegerField(choices=[('1', 'General'), ('2', 'Equipment'), ('3', 'Disemination'), ('4', 'Doctoral')], default=1)),
                ('label', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('depends_on', models.ManyToManyField(related_name='_item_depends_on_+', to='workplan.Item')),
                ('parent', models.ManyToManyField(related_name='children', to='workplan.Item')),
                ('who', models.ManyToManyField(related_name='workplan_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
