# Generated by Django 3.1.6 on 2022-11-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplan', '0002_auto_20221102_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['start']},
        ),
    ]
