# Generated by Django 3.1.6 on 2021-05-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=4)),
                ('is_protein', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residues', to='pdbase.chain')),
            ],
        ),
        migrations.AddField(
            model_name='chain',
            name='pdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='pdbase.pdb'),
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('bfactor', models.FloatField()),
                ('residue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atoms', to='pdbase.residue')),
            ],
        ),
    ]
