# Generated by Django 3.1.6 on 2021-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
