# Generated by Django 3.1.6 on 2021-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0002_auto_20210528_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
