# Generated by Django 3.1.6 on 2022-08-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msa', '0001_initial'),
        ('pdbase', '0003_pdb_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='msa_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aligned_residues', to='msa.position'),
        ),
    ]
