# Generated by Django 3.1.6 on 2023-03-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0004_residue_msa_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residue',
            options={'ordering': ['num']},
        ),
    ]
