# Generated by Django 3.1.6 on 2023-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbase', '0005_auto_20230303_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='oligomer',
            field=models.TextField(null=True),
        ),
    ]
